// components/Universe.vue
<template>
  <div>
    <!-- <div id='fps'></div> -->
    <canvas id='canvas' ref='Universe' style='width: 100% height: 100%'></canvas>
    <p>{{ message }}</p>
  </div>
</template>

<script>
import { Renderer } from '../www/render';

export default {
  props: ['node', 'renderer', 'memory', 'life'],
  data() {
    return {
      message: "",
    };
  },
  mounted() {
    this.canvas = this.$refs['Universe'];
    this.ctx = this.canvas.getContext('2d');

    const Life = this.life;
    const renderer = this.renderer;
    var node = this.node;

    renderer.zoom_to(2);
    var fps = 1000;
    var playing = false;
    var step = 1;

    this.lastFrame = performance.now();
    this.frames = [];
    this.lastFrameTimeStamp = performance.now();
    
    const render = () => {
      const canvas_width = document.body.scrollWidth;
      const canvas_height = document.body.scrollHeight;
      this.canvas.width = canvas_width;
      this.canvas.height = canvas_height;

      renderer.set_size(canvas_width, canvas_height, window.devicePixelRatio);

      if (this.queue_draw_cells.length > 0) {
        for (var x = 0; x < this.queue_draw_cells.length; x++) {
          renderer.draw_cell(this.queue_draw_cells[x][0], this.queue_draw_cells[x][1])
        }
        this.queue_draw_cells = [];
      }

      if (this.queue_set_cells.length > 0) {
        for (var x = 0; x < this.queue_set_cells.length; x++) {
          node = Life.set_cell(node, this.queue_set_cells[x][0], this.queue_set_cells[x][1], this.queue_set_cells[x][2]);
        }
        this.queue_set_cells = [];
      }

      const imagePtr = renderer.get_image_data(node);
      const image_data_array = new Uint8ClampedArray(this.memory.buffer, imagePtr, canvas_width * canvas_height * 4);

      const image_data = new ImageData(image_data_array, canvas_width, canvas_height);
      this.ctx.putImageData(image_data, 0, 0);

      const now = performance.now();
      const delta = now - this.lastFrameTimeStamp;
      this.lastFrameTimeStamp = now;
      const fps = 1 / delta * 1000;
      this.frames.push(fps);
      if (this.frames.length > 100) {
        this.frames.shift();
      }
  
      let min = Infinity;
      let max = -Infinity;
      let sum = 0;
      for (let i = 0; i < this.frames.length; i++) {
        sum += this.frames[i];
        min = Math.min(this.frames[i], min);
        max = Math.max(this.frames[i], max);
      }
      let mean = sum / this.frames.length;
  
      this.message = `
      Frames per Second:
      latest = ${Math.round(fps)}
      avg of last 100 = ${Math.round(mean)}
      min of last 100 = ${Math.round(min)}
      max of last 100 = ${Math.round(max)}
      `.trim();
    };

    const advance = () => {
      node = Life.advance(node, step);
      render();
    };

    // temporary solution for unknown root cause
    const settleFrames = setInterval(render, 1000 / fps);
    setTimeout(() => {
      clearInterval(settleFrames);
    }, 1000);

    this.$nuxt.$on('playing', ($event) => {
      if ($event) {
        playing = true;
        this.animationLoop = setInterval(advance, 1000 / fps);
      }
      else {
        playing = false;
        clearInterval(this.animationLoop);
      }
    });

    this.$nuxt.$on('updateNode', ($event) => {
      node = $event;
      renderer.zoom_to(33);
      renderer.set_size(document.body.scrollWidth, document.body.scrollHeight, window.devicePixelRatio);
      renderer.center_view();

      $nuxt.$emit('centerView');
      if (!playing) render();
    });

    this.$nuxt.$on('advance', () => {
      advance(step);
      if (!playing) render();
    });

    this.$nuxt.$on('doOffset' , ($event) => {
      switch ($event) {
        case 'left':
          renderer.move_offset(-100, 0);
          break;
        case 'right':
          renderer.move_offset(100, 0);
          break;
        case 'up':
          renderer.move_offset(0, -100);
          break;
        case 'down':
          renderer.move_offset(0, 100);
          break;
        default:
          break;
      }
      if (!playing) render();
    });

    this.$nuxt.$on('zoomOut', ($event) => {
      renderer.zoom_centered($event);
      if (!playing) render();
    });

    this.$nuxt.$on('centerView', () => {

      console.log(window.performance.now());
      const bounds = Life.get_bounds(node);

      console.log(bounds);
      const center_x = (bounds[0] + bounds[1]) / 2;
      const center_y = (bounds[2] + bounds[3]) / 2;

      console.log(`${center_x}, ${center_y}`);

      const move_x = (-center_x * renderer.get_cell_width() * 1.1) + (document.body.scrollWidth / 2);
      const move_y = (-center_y * renderer.get_cell_width() * 1.1) + (document.body.scrollHeight / 2);

      console.log(`${move_x}, ${move_y}`);

      renderer.center_view();
      renderer.move_offset(node, move_x, move_y);

      console.log(window.performance.now());

      if (!playing) render();
    });

    function getMousePos(canvas, evt) {
      var rect = canvas.getBoundingClientRect();
      return {
        x: evt.clientX - rect.left,
        y: evt.clientY - rect.top
      };
    }

    var last_mouse_x = null;
    var last_mouse_y = null;
    const drag = (e) => {
      if (last_mouse_x !== null) {
        let dx = Math.round(e.clientX - last_mouse_x);
        let dy = Math.round(e.clientY - last_mouse_y);
        renderer.move_offset(dx, dy);
        last_mouse_x += dx;
        last_mouse_y += dy;
      }
    };

    this.queue_draw_cells = [];
    this.queue_set_cells = [];
    const draw = (e) => {
      const mouse_pos = getMousePos(this.canvas, e);
      var coords = renderer.pixel_to_cell(mouse_pos.x, mouse_pos.y);
      // console.log(`${coords[0]}, ${coords[1]}`);

      this.queue_draw_cells = [];
      this.queue_draw_cells.push(coords);

      this.queue_set_cells = [];
      this.queue_set_cells.push([...coords, true]);

      // console.log(Life.is_alive(node, coords[0], coords[1]));

      if (!playing) render();
    }

    this.canvas.onmousedown = (e) => {
      e.preventDefault();

      if (!playing) {
        this.renderLoop = setInterval(render, 1000 / fps);
      }

      if (e.which === 3 || e.which === 2) {
        this.canvas.addEventListener('contextmenu', (e) => e.preventDefault());

        if (renderer.get_cell_width() >= 1) {
          window.addEventListener('mousemove', draw, true);
        }
      }
      if (e.which === 1) {
        last_mouse_x = e.clientX;
        last_mouse_y = e.clientY;
        window.addEventListener('mousemove', drag, true);
      }
      return false;
    };

    window.onmouseup = () => {
      last_mouse_x = null;
      last_mouse_y = null;
      this.queue_draw_cells = [];
      window.removeEventListener('mousemove', draw, true);
      window.removeEventListener('mousemove', drag, true);
      this.canvas.removeEventListener('contextmenu', (e) => e.preventDefault());

      clearInterval(this.renderLoop);
      render();
    };

    this.canvas.onmousewheel = (e) => {
      e.preventDefault();
      const mouse_pos = getMousePos(this.canvas, e);
      renderer.zoom_at((e.wheelDelta || -e.detail) < 0, mouse_pos.x, mouse_pos.y);
      if (!playing) render();
      return false;
    };

    window.addEventListener('resize', () => {
      if (!playing) render();
    }, true);
  },

  destroy() {
    window.removeEventListener('mousemove', draw, true);
    window.removeEventListener('mousemove', drag, true);
    window.removeEventListener('resize', () => {
      if (!playing) render();
    }, true);
    this.canvas.removeEventListener('contextmenu', (e) => e.preventDefault());

    clearInterval(this.animationLoop)
    clearInterval(this.renderLoop);
  }
};
</script>

<style>
body {
  margin: 0 !important;
  padding: 0 !important;
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
#fps {
  white-space: pre;
  font-family: monospace;
}

#canvas {
  width: 100%;
  height: 100%;
  display: block;
}
</style>

// src/Universe.jsx
import { useState, useEffect, useRef } from 'react'
import Controls from './Controls';

function Universe({ Life, Renderer, memory }) {
  const canvasRef = useRef(null);
  const isStepping = useRef(false);
  const animationFrame = useRef(null);
  const queueDrawCell = useRef(null);
  const queueSetCells = useRef([]);
  const lastMousePos = useRef(null);

  const [playing, _setPlaying] = useState(false);
  const playingRef = useRef(playing);
  const setPlaying = (data) => {
    playingRef.current = data;
    _setPlaying(data);
  }

  const [fpsInfo, setFpsInfo] = useState('');

  function loadRle(pattern) {
    const items = Life.parse_rle(pattern);
    Life.construct(items);
  }

  function resizeCanvas() {
    const canvas = canvasRef.current;
    const width = document.documentElement.clientWidth;
    const height = document.documentElement.clientHeight;
    canvas.width = width;
    canvas.height = height;
    Renderer.set_size(canvas.width, canvas.height, 1);
    // Renderer.set_size(canvas.width, canvas.height, window.devicePixelRatio);
    if (!playing) draw();
  }

  function offset(direction) {
    switch (direction) {
      case 'up':
        Renderer.move_offset(0, 100);
        break;
      case 'down':
        Renderer.move_offset(0, -100);
        break;
      case 'left':
        Renderer.move_offset(100, 0);
        break;
      case 'right':
        Renderer.move_offset(-100, 0);
        break;
    }
    if (!playing) draw();
  }

  function zoomOut(out) {
    Renderer.zoom_centered(out);
    if (!playing) draw();
  }

  function step() {
    Life.advance(1);
    if (!playing) draw();
  }

  function centerView() {
    const bounds = Life.get_bounds();
    const width = Math.ceil((bounds[0] - bounds[1]) * 1.1);
    const height = Math.ceil((bounds[2] - bounds[3]) * 1.1);

    const width_factor = Math.abs(document.documentElement.clientWidth / width);
    const height_factor = Math.abs(document.documentElement.clientHeight / height);
    const factor = Math.min(width_factor, height_factor);

    var new_cell_width = 1;
    if (factor > 1) {
      while (new_cell_width < factor) {
        new_cell_width *= 2;
      }
      new_cell_width /= 2;
    }
    else {
      while (new_cell_width > factor) {
        new_cell_width /= 2;
      }
    }

    var center_x = (bounds[0] + bounds[1]) / 2;
    var center_y = (bounds[2] + bounds[3]) / 2;

    if (0.1 * new_cell_width < 1) {
      center_x = Math.round(center_x * new_cell_width);
      center_y = Math.round(center_y * new_cell_width);
    }
    else {
      center_x = Math.round((center_x * new_cell_width * 1.1));
      center_y = Math.round((center_y * new_cell_width * 1.1));
    }

    Renderer.zoom_to(new_cell_width);
    Renderer.center_view(center_x, center_y);
    if (!playing) draw();
  }

  function getMousePos(canvas, event) {
    const rect = canvas.getBoundingClientRect();
    return {
      x: event.clientX - rect.left,
      y: event.clientY - rect.top
    };
  }

  const drag = (e) => {
    if (lastMousePos !== null) {
      let dx = Math.round(e.clientX - lastMousePos[0]);
      let dy = Math.round(e.clientY - lastMousePos[1]);
      Renderer.move_offset(dx, dy);
      lastMousePos[0] += dx;
      lastMousePos[1] += dy;
    }
  }

  const drawCells = (e) => {
    const mouse_pos = getMousePos(canvasRef.current, e);

    queueDrawCell.current = [mouse_pos.x, mouse_pos.y];

    queueSetCells.current.push([mouse_pos.x, mouse_pos.y, true]);
  }
  
  function playLoop() {
    if (isStepping.current) {
      step();
    }
    draw();
    animationFrame.current = requestAnimationFrame(playLoop);
  }

  function play(play) {
    if (play) {
      animationFrame.current = requestAnimationFrame(playLoop);
    }
    else {
      cancelAnimationFrame(animationFrame.current);
      animationFrame.current = null;
    }
  }

  function playWithStep(step) {
    isStepping.current = step;
    play(step);
    setPlaying(step);
  }

  function draw() {
    if (queueDrawCell.current) {
      Renderer.draw_cell(queueDrawCell.current[0], queueDrawCell.current[1])
    }

    if (queueSetCells.current.length > 0) {
      for (let x = 0; x < queueSetCells.current.length; x++) {
        Life.set_cell(queueSetCells.current[x][0], queueSetCells.current[x][1], queueSetCells.current[x][2]);
      }
      queueSetCells.current = [];
    }

    const canvas = canvasRef.current;
    const context = canvas.getContext('2d');

    const width = canvas.width;
    const height = canvas.height;
    const imagePtr = Renderer.get_image_data();
    const imageDataArray = new Uint8ClampedArray(memory.buffer, imagePtr, width * height * 4);
    const imageData = new ImageData(imageDataArray, width, height);
    context.putImageData(imageData, 0, 0);
  }
  
  useEffect(() => {
    // glider
    // const items = [0, 0, 1, 1, 2, 1, 2, 0, 2, -1];

    // acorn
    // const acorn = [0, 0, 1, 0, 1, -2, 3, -1, 4, 0, 5, 0, 6, 0];

    // pulsar
    const pulsar = [1, 2, 1, 3, 1, 4, 2, 1, 3, 1, 4, 1, 1, -2, 1, -3, 1, -4, 2, -1, 3, -1, 4, -1, 
                    -1, -2, -1, -3, -1, -4, -2, -1, -3, -1, -4, -1, -1, 2, -1, 3, -1, 4, -2, 1, -3, 1, -4, 1, 
                    2, 6, 3, 6, 4, 6, 2, -6, 3, -6, 4, -6, -2, -6, -3, -6, -4, -6, -2, 6, -3, 6, -4, 6,
                    6, 2, 6, 3, 6, 4, 6, -2, 6, -3, 6, -4, -6, 2, -6, 3, -6, 4, -6, -2, -6, -3, -6, -4];

    // gosper gun
    const items = [24, 0, 22, 1, 24, 1, 12, 2, 13, 2, 20, 2, 21, 2, 34, 2, 35, 2, 11, 3, 15, 3, 20, 3, 21, 
      3, 34, 3, 35, 3, 0, 4, 1, 4, 10, 4, 16, 4, 20, 4, 21, 4, 0, 5, 1, 5, 10, 5, 14, 5, 16, 5, 17, 5, 22, 
      5, 24, 5, 10, 6, 16, 6, 24, 6, 11, 7, 15, 7, 12, 8, 13, 8];

    for (let x = 0; x < pulsar.length; x += 2) {
      items.push(pulsar[x] + 50, pulsar[x + 1]);
      items.push(pulsar[x] - 20, pulsar[x + 1]);
    }

    Life.construct(items);
    console.log(Life.level());
    console.log(Life.expand());
    console.log(Life.convert_rle(Life.expand(), 'gosper gun'));

    resizeCanvas();
    centerView();
    draw();

    const canvas = canvasRef.current;

    canvas.onmousedown = (e) => {
      e.preventDefault();

      if (e.which === 3 || e.which === 2) {
        canvas.addEventListener('contextmenu', (e) => e.preventDefault());

        if (Renderer.get_cell_width() >= 1) {
          drawCells(e);
          window.addEventListener('mousemove', drawCells, true);
        }
      }
      if (e.which === 1) {
        lastMousePos[0] = e.clientX;
        lastMousePos[1] = e.clientY;
        window.addEventListener('mousemove', drag, true);
      }

      if (!playingRef.current) {
        isStepping.current = false;
        play(true);
      }
      return false;
    };

    window.onmouseup = () => {
      lastMousePos.current = null;
      queueDrawCell.current = null;
      window.removeEventListener('mousemove', drawCells, true);
      window.removeEventListener('mousemove', drag, true);
      canvas.removeEventListener('contextmenu', (e) => e.preventDefault());
      if (!playingRef.current) {
        play(false);
        draw()
      };
    };

    canvas.addEventListener('contextmenu', (e) => e.preventDefault());
    
    canvas.onmousewheel = (e) => {
      e.preventDefault();
      const mouse_pos = getMousePos(canvas, e);
      Renderer.zoom_at((e.wheelDelta || -e.detail) < 0, mouse_pos.x, mouse_pos.y);
      draw();
      return false;
    };

    window.addEventListener('resize', () => resizeCanvas());

    return () => {
      play(false);
      window.removeEventListener('resize', () => resizeCanvas());
      window.removeEventListener('mousemove', draw, true);
      window.removeEventListener('mousemove', drag, true);
      canvas.removeEventListener('contextmenu', (e) => e.preventDefault());
    }
  }, []);

  return (
    <div className="Universe">
      <Controls 
        offset={offset}
        zoomOut={zoomOut}
        centerView={centerView}
        step={step}
        play={playWithStep}
        playing={playing}
      />
      <canvas className='Canvas' ref={canvasRef} />
      {/* <p>fpsInfo</p> */}
    </div>
  )
}

export default Universe
